### ISSUE TITLE
Priorities + plan

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#19]
On Sunday I am starting work with the Waorani to enter their mapping information into this editor. Here are the priorities, in order, for getting things done by then.

[**Top Priority**](https://github.com/digidem/ecuador-map-editor/milestones/Priority)
- [x] Fix segfault on sync #18 - essential, right now I can't synchronize / replicate at all.
- [x] Import shp file #15 we don't necessarily need a UI, we just need to get one shapefile (a river dataset) into the database as a starting point.
- [x] Point `localhost/tiles` to folder in `UserData` and read `imagery.json` from there too #8. We can manually manage these without a UI for now.
- [x] Fix packaging, merge #13. In `master` we still see strange rendering funkiness which is fixed in `packaged` branch.
- [x] Get at least a folder picker dialog #6.

I'll deal with #7 

[**Next week**](https://github.com/digidem/ecuador-map-editor/milestones/next)
- [x] Let's get a packaging script that creates a single installer.
- [x] Have a way to import a `tar.gz` of map tiles and modify `imagery.json` automatically #8

[**Later**](https://github.com/digidem/ecuador-map-editor/milestones/later)
https://github.com/digidem/ecuador-map-editor/milestones/later

**Comment by substack** [comment]
* [x] import shp file

You can do this by sending a PUT request directly to `/import.shp`:

```
$ curl -T 50m_physical.zip http://localhost:5000/import.shp
```

**Comment by substack** [comment]
* [x] folder picker dialog
