### ISSUE TITLE
Make MD Territory Changeset comment optional

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop#642]
[**Description**
](url)Currently, in order to save changes in Mapeo Desktop Territory, one is required to enter a Changeset Comment. This behavior is a holdover from iD editor and doesn't seem necessary to require for our partner workflows. What's more, Changeset log isn't accessible anywhere in the UI and would require some digging into the Mapeo system files to find, hence our partners report having trouble explaining the justification of this behavior during trainings.

Our partners do mention that it *could* be useful to log saved changes for some workflows, but not always, and only if they could actually access it via the UI.

**Todo**

Without delving into UX work about provisioning the changeset on the front end, let's at least take on the `nugget` of making the Changeset Comment optional, so that a user can save their changes without entering anything in the text box.

## Acceptance criteria:

- [ ]  A user is able to click the save button in MD Territory Save your Edits view without adding anything into the Changeset Comment box
- [ ]  Change `(required)` to `(optional)` in the Changeset Comment Textbox hint string.
- [ ]  Bonus: remove `Download osmChange file` download link since this file is not directly useful to our users, and leaves the false impression that it's the changelog itself.
