### ISSUE TITLE
(Front) Practice Mode + Explainer screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop#649]
**Description**
As with mobile, first time users of MD will automatically fall into practice mode.
The orange "Practice Mode" bar will clickable
Once user clicks on the bar, open a modal displaying text explaining what is practice mode. Copy TBD

**Design** 
https://www.figma.com/file/ZOsM89L0xy0NUOCkuksJgq/OTF-%2B-UXFund?node-id=47885%3A1423

**Todo**

- [ ] Add Practice Mode
- [ ] Made Practice Mode bar clickable
- [ ] Display modal (with copy TBD) once practice mode is clicked
