### ISSUE TITLE
Mapeo for ICCAs release

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#682]
Tracking tasks for the Mapeo for ICCAs release:

- [x] Review & merge PR to fix the default filters shown in Observation view ([#680](https://github.com/digidem/mapeo-desktop/pull/680))
- [x] Merge CrowdIn updates ([#623](https://github.com/digidem/mapeo-desktop/pull/623))
- [x] Wait on fixes to updated ICCA form; approve & merge ([#677](https://github.com/digidem/mapeo-desktop/pull/677)) (@rainbowgiantsquid)
- [x] Update [`mapeo-config-icca`](https://github.com/digidem/mapeo-config-icca) to ~~v1.5.0~~ v1.6.0
- [ ] wait on translations from WCMC
- [ ] wait on new published version of mapeo-config-icca once translations are done, then update here
