### ISSUE TITLE
Upgrage Electron and Bundler

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-desktop#715]
To be compatible with the new `Mapeo Core`, the Electron version needs to be upgraded to version 22.0.3

As well, the current bundler (webpack) can be replaced with [Vite-Electron](https://evite.netlify.app/).

## Requirements
- [ ] Electron Version: 22.0.3
- [ ] Typescript Compatible
- [ ] Hot Reloading

This electron version requires node v 16.17.1

**Comment by ErikSin** [comment]
## Upgrading Electron

- `eslint-plugin-flowtype` incompatible - was removed
- `react-intl-formatted-duration` required peer dependency `react-intl` >=v4 . Upgraded `react-intl` from 3.2.4 to 4.7.6. [Breaking API changes](https://formatjs.io/docs/react-intl/upgrade-guide-4x) in `react-intl` do not apply to anything in our codebase

**Comment by ErikSin** [comment]
## Breaking changes from v9 to v22

### [v10](https://releases.electronjs.org/release/v10.0.0)
- [ ] Changed the default value of 'enableRemoteModule' to false. [#22091](https://github.com/electron/electron/pull/22091)
- [ ] Changed the default value of app.allowRendererProcessReuse to true, this will prevent loading of non-context-aware native modules in renderer processes. See #18397 for more information on this change. [#22336](https://github.com/electron/electron/pull/22336)
- [ ] Fixed the positioning of window buttons on MacOS when the OS locale is set to an RTL language (like Arabic or Hebrew). Frameless window apps may have to account for this change while styling their windows. [#22016](https://github.com/electron/electron/pull/22016)

### [v11](https://releases.electronjs.org/release/v11.0.0)
- [ ] Removed experimental APIs: BrowserView.{destroy, fromId, fromWebContents, getAllViews} and the id property of BrowserView. [#23578](https://github.com/electron/electron/pull/23578)

### [v12](https://releases.electronjs.org/release/v12.0.0)

### [v13](https://releases.electronjs.org/release/v13.0.0)

### [v14](https://releases.electronjs.org/release/v14.0.0)

### [v15](https://releases.electronjs.org/release/v15.0.0)

### [v16](https://releases.electronjs.org/release/v16.0.0)

### [v17](https://releases.electronjs.org/release/v17.0.0)

### [v18](https://releases.electronjs.org/release/v18.0.0)

### [v19](https://releases.electronjs.org/release/v19.0.0)

### [v20](https://releases.electronjs.org/release/v20.0.0)

### [v21](https://releases.electronjs.org/release/v21.0.0)

### [v22](https://releases.electronjs.org/release/v22.0.0)

**Comment by ErikSin** [comment]
Work on [this branch](https://github.com/digidem/mapeo-desktop/tree/es/chore-electron-upgrade)

**Comment by achou11** [comment]
after pairing with Erik yesterday, the following issues were addressed:

- fixing @mapeo/map-server + better-sqlite3 integration
- using @electron/remote instead of now removed remote api from electron (not sure if fully resolved yet)
- fixing electron-is-dev usage (due to electron remote issue)

**Comment by achou11** [comment]
another pairing session with Erik today. the following issues were addressed:

- fixed an issue where the map server creation would crash if the electron directory didn't exist yet
- fixed issue with importing the @electron/remote in the renderer. required using `import * as remote` syntax

the app runs locally now! was even able to sync a small amount of data with my phone.

next steps are more thorough testing and figuring out what's broken. 

![image](https://user-images.githubusercontent.com/18542095/216451363-8a0cc9d8-b781-473f-b359-a2fb3507e9df.png)

separately, wondering if the map server directory `background-maps` should not be living in the user data directory in development, or if that's okay. could be pretty catastrophic for people who use the map server in production mapeo and also develop Mapeo locally, which is an almost-zero number of people right now 😅

**Comment by achou11** [comment]
after playing around with Vite and some vite electron plugins, thinking that this issue should be split into two items:

1. Electron upgrade
2. Bundler upgrade

To my knowledge, upgrading Electron can be done independently without requiring major changes to our frontend setup. For the sake of better isolating these major changes, doing them separately will be easier to manage and review.

Additionally, thinking that Vite may not be the option we want to use after my explorations. There's some deceptive complexity with it that I haven't fully managed to wrap my head around. Wondering if we can achieve 80% with just using Rollup and relevant plugins at the expense of some of the dev experience that Vite provides (when it works). Something to discuss in more detail

**Comment by ErikSin** [comment]
Closing ticket, and replacing with #726
