### ISSUE TITLE
Update Mapbox token v2

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop#755]
**Describe the bug**
See mobile issue here https://github.com/digidem/mapeo-mobile/issues/1147

**Todo**

- [ ]  create release based on branch off 5.6
- [ ]  new code signing certificate for windows
- [ ]  update notarizing for apple

**Issues to consider**
https://github.com/digidem/mapeo-desktop/issues/750
