### ISSUE TITLE
Update Mapbox token v1

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop#756]
## Description

Full bug here :  https://github.com/digidem/mapeo-desktop/issues/755
Since the proper fix can require quite of few days of work, and since this fix is urgent, here is a proposed patch release:

## Todo

- [x] Update the token
- [x] Update build step as a secret in CI
- [x] Make sure it doesn't update the files that the Autoupdater uses - https://github.com/digidem/mapeo-desktop/issues/750
  - technical note: might be as simple as adding `publishAutoUpdate: false` [here](https://github.com/digidem/mapeo-desktop/blob/master/builder.config.js#L54-L58)

Once the above items are done, can publish a patch release that branches off from the most recent patch release branch (we don't want to include recent commits on master branch that have not been tested/QA'd)

## User impact

Due to time constraints, this release will not be code-signed/notarized. Users should expect the following in order to run the app after installing:

- on Windows: They will get a warning of potential malicious software

- On Mac: They will need to right+click press and Open, instead of just clicking the icon to open
- Mapeo Desktop will not auto-update, it will require a manual update to get this fix

**Comment by achou11** [comment]
Closing as this has now been addressed by the changes found on this branch:

https://github.com/digidem/mapeo-desktop/tree/v5.6.3/fix-mapbox-token

`v5.6.3` tag was pushed to this branch to create the release

`publishAutoUpdate: false` seems to have worked as well (no `latest.yml` file uploaded to S3)
